# Generated by Django 4.2.29 on 2026-04-02 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("bio", models.TextField(blank=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("death_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "preferred_languages",
                    models.CharField(blank=True, default="en", max_length=100),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                ("newsletter_subscription", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_active", models.DateTimeField(auto_now=True)),
                (
                    "favorite_authors",
                    models.ManyToManyField(
                        blank=True, related_name="user_profiles", to="books.author"
                    ),
                ),
                (
                    "favorite_genres",
                    models.ManyToManyField(
                        blank=True, related_name="user_profiles", to="books.genre"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=50)),
                ("model_type", models.CharField(max_length=50)),
                (
                    "training_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "training_data_size",
                    models.IntegerField(
                        help_text="Number of ratings used for training"
                    ),
                ),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-training_date"],
                "indexes": [
                    models.Index(
                        fields=["name", "version"], name="books_model_name_bac11a_idx"
                    ),
                    models.Index(
                        fields=["is_active", "-training_date"],
                        name="books_model_is_acti_6c8c8e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "isbn",
                    models.CharField(max_length=13, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=500)),
                ("publisher", models.CharField(blank=True, max_length=200, null=True)),
                ("publication_year", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("page_count", models.IntegerField(blank=True, null=True)),
                ("language", models.CharField(blank=True, default="en", max_length=50)),
                ("isbn_13", models.CharField(blank=True, max_length=13, null=True)),
                ("lccn", models.CharField(blank=True, max_length=20, null=True)),
                ("oclc_number", models.CharField(blank=True, max_length=20, null=True)),
                ("subjects", models.TextField(blank=True)),
                ("image_url_small", models.URLField(blank=True, null=True)),
                ("image_url_medium", models.URLField(blank=True, null=True)),
                ("image_url_large", models.URLField(blank=True, null=True)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "authors",
                    models.ManyToManyField(related_name="books", to="books.author"),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True, related_name="books", to="books.genre"
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="UserInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("view", "Viewed Book"),
                            ("click", "Clicked Recommendation"),
                            ("wishlist", "Added to Wishlist"),
                            ("cart", "Added to Cart"),
                            ("purchase", "Purchased"),
                            ("share", "Shared"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="books_useri_user_id_3dda53_idx",
                    ),
                    models.Index(
                        fields=["book", "timestamp"],
                        name="books_useri_book_id_f962a1_idx",
                    ),
                    models.Index(
                        fields=["interaction_type", "timestamp"],
                        name="books_useri_interac_d86426_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RecommendationFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("was_helpful", models.BooleanField()),
                ("feedback_text", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_feedback",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="books_recom_user_id_376063_idx",
                    )
                ],
                "unique_together": {("user", "book")},
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="Rating from 1 to 5",
                    ),
                ),
                ("review", models.TextField(blank=True)),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "book"], name="books_ratin_user_id_ca2f72_idx"
                    ),
                    models.Index(
                        fields=["date_created"], name="books_ratin_date_cr_6572e4_idx"
                    ),
                ],
                "unique_together": {("user", "book")},
            },
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["title"], name="books_book_title_d3218d_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["publication_year"], name="books_book_publica_75adf4_idx"
            ),
        ),
    ]
